scoreboard:
  title: '&5mood&fhc'
  scores:
    10: '&7· &fᴘᴏᴛʀᴢᴇʙᴜᴊᴇsᴢ ᴘᴏᴍᴏᴄʏ?'
    9: '&7· &fᴡʙɪᴊᴀᴊ &b/ᴅɪsᴄᴏʀᴅ'
    8: ' '
    7:  '    &fᴅᴏꜱᴛᴇᴘɴᴇ ᴛʀʏʙʏ:'
    6:  '    &7· &4ʙᴏxᴘᴠᴘ: &f%bungee_boxpvp%'
    5: '    &7· &aꜱᴜʀᴠɪᴠᴀʟ: &f%bungee_survival%'
    4: ' '
    3: '&5ᴡᴡᴡ.ᴍᴏᴏᴅʜᴄ.ᴘʟ'
    2: '&bᴡᴡᴡ.ᴍᴏᴏᴅʜᴄ.ᴘʟ/ᴅɪꜱᴄᴏʀᴅ'
    1: '&6ᴛɪᴋᴛᴏᴋ.ᴄᴏᴍ/@ᴍᴏᴏᴅʜᴄ'